version: "3.9"

services:

  drkiq:
    image: ramonpm/dockerails:1.0
    volumes:
      - ./drkiq:/opt/app
    ports:
      - '3000:3000'
  
  nginx:
    image: ramonpm/nginx:1.0
    links:
      - drkiq
    ports:
      - '80:8020'
