version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: drkiq
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - drkiq-postgres:/var/lib/postgresql/data

  drkiq:
    image: ramonpm/dockerails
    volumes:
      - ./drkiq:/opt/app
    ports:
      - '8020:8020'
